server:
  port: 80
spring:
  datasource:
    # 数据源基本配置
    username: spring
    password: 231316
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://tools.chuhelan.com:3306/spring?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
  thymeleaf:
    prefix: classpath:/templates/
mybatis:
  type-aliases-package: com.chuhelan.htg.beans #所有Entity别名类所在包
  mapper-locations: [ classpath:mapper/**/*.xml ]
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
